default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: voter_media_development
  username: postgres
  password: 123456789
  host: localhost
# production:
#   <<: *default
#   database: voter_media_development
#   username: postgres!
#   password: postgres!
#   host: localhost

  # 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
#  https://github.com/rorong/company.git 
# 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  
# gurpreet_ongraph/ TataAltroz@2022#

# Provide multiselect services -- may be we need a middle column 
# ssh rordev@162.243.172.109

# development:
#   adapter:  mysql
#   database: voter_dev
#   username: root
#   password: 123456789

# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password: 123456789
#   host: localhost

# development:
#   <<: *default
#   database: votermedia_development

# test:
#   <<: *default
#   database: mydatabase_test

# production:
#   <<: *default
#   database: mydatabase_production
#   username: root
#   password: <%= ENV['MYDATABASE_PASSWORD'] %>
#   host: <%= ENV['MYDATABASE_HOST'] %>
